#!/usr/bin/env node
// Repository-native SVG branding. Counts come from the generated indexes and JSONL.
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadSkillRepos } from './load-skill-repos.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'assets', 'brand');
const lang = process.argv.find(arg => arg.startsWith('--lang='))?.slice(7) || process.env.SKILL_LANG;
if (!['en', 'zh'].includes(lang)) {
  console.error('Usage: node scripts/build-brand.mjs --lang=en|zh');
  process.exit(2);
}
const [skills, graph, marketplace, repos] = await Promise.all([
  fs.readFile(path.join(ROOT, 'INDEX', 'search.json'), 'utf8').then(JSON.parse),
  fs.readFile(path.join(ROOT, 'INDEX', 'graph.json'), 'utf8').then(JSON.parse),
  fs.readFile(path.join(ROOT, '.claude-plugin', 'marketplace.json'), 'utf8').then(JSON.parse),
  loadSkillRepos(),
]);
const stats = { skills: skills.length, edges: graph.edges.length, volumes: marketplace.plugins.length, repos: repos.length };
if (new Set(skills.map(skill => skill.name)).size !== stats.skills || graph.nodes.length !== stats.skills)
  throw new Error('Skill and graph indexes must agree before rendering the brand assets.');
const esc = text => String(text).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const fmt = n => n.toLocaleString('en-US');
const [logo, staticLogo] = await Promise.all(['logo.svg', 'logo-static.svg'].map(name => fs.readFile(path.join(OUT, name), 'utf8')));
function logoAt(x, y, size, animated = true) {
  // Embed vector source rather than an external SVG resource: image-mode SVGs
  // cannot load external resources. Prefix the animation name to avoid collisions.
  return (animated ? logo : staticLogo)
    .replace('viewBox="0 0 192 192"', `x="${x}" y="${y}" viewBox="0 0 192 192"`)
    .replace('width="192" height="192"', `width="${size}" height="${size}"`)
    .replaceAll('breathe', 'logo-breathe');
}
const css = `
  .sans { font-family: 'Segoe UI', Arial, sans-serif; }
  .serif { font-family: Georgia, 'Times New Roman', serif; }
  .mono { font-family: 'Courier New', monospace; }
  .travel { stroke-dasharray: 14 100; animation: travel 12s linear infinite; }
  .breathe { transform-box: fill-box; transform-origin: center; animation: breathe 8s ease-in-out infinite; }
  @keyframes travel { to { stroke-dashoffset: -228; } }
  @keyframes breathe { 0%, 100% { opacity: .65; } 50% { opacity: 1; } }
  @media (prefers-reduced-motion: reduce) { .travel, .breathe { animation: none; } }
`;
const wrap = (w, h, title, description, body, animated = true) => `<!-- Generated by scripts/build-brand.mjs; do not edit by hand. -->
<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" role="img" aria-labelledby="title description">
  <title id="title">${esc(title)}</title>
  <desc id="description">${esc(description)}</desc>
  <style>${animated ? css : css.replace(/  \.travel[\s\S]*$/, '')}</style>
${body}
</svg>
`;

function hero(animated = true) {
  const volumes = ['META', 'DOCS', 'CODE', 'DATA', 'AI', 'BIZ', 'ART', 'WORK', 'SAFE', 'FIELD', 'PLATFORM'];
  const nodes = volumes.map((label, i) => {
    const angle = (-90 + i * 360 / volumes.length) * Math.PI / 180;
    return { x: 982 + Math.cos(angle) * 120, y: 176 + Math.sin(angle) * 120, label, i };
  });
  const spokes = nodes.map(n => `<path d="M982 176 L${n.x.toFixed(2)} ${n.y.toFixed(2)}" stroke="#385348" stroke-width="1"/>`).join('\n');
  const edges = nodes.filter(n => n.i % 2 === 0).map(n => {
    const target = nodes[(n.i + 3) % nodes.length];
    return `<path d="M${n.x.toFixed(2)} ${n.y.toFixed(2)} Q982 176 ${target.x.toFixed(2)} ${target.y.toFixed(2)}" fill="none" stroke="#deb46c" stroke-opacity=".22"/>`;
  }).join('\n');
  const labels = nodes.map(n => {
    const a = Math.atan2(n.y - 176, n.x - 982);
    const x = 982 + Math.cos(a) * 145, y = 176 + Math.sin(a) * 143;
    return `<g><circle cx="${n.x.toFixed(2)}" cy="${n.y.toFixed(2)}" r="${n.i % 3 ? 4 : 6}" fill="${n.i % 3 === 0 ? '#deb46c' : '#90b8a7'}" class="breathe" style="animation-delay: -${n.i}s"/><text x="${x.toFixed(2)}" y="${y.toFixed(2)}" fill="#a8b9ae" text-anchor="middle" dominant-baseline="middle" class="mono" font-size="9.5" letter-spacing="1">${n.label}</text></g>`;
  }).join('\n');
  const body = `  <defs>
    <pattern id="grid" width="32" height="32" patternUnits="userSpaceOnUse"><path d="M32 0H0V32" fill="none" stroke="#f3eddc" stroke-opacity=".032"/></pattern>
  </defs>
  <rect width="1200" height="360" rx="20" fill="#111d1a"/>
  <rect x="1" y="1" width="1198" height="358" rx="19" fill="url(#grid)" stroke="#30473c"/>
  <path d="M44 44H69 M44 44V69 M1156 316H1131 M1156 316V291" stroke="#deb46c" stroke-opacity=".6" fill="none"/>
  <text x="66" y="72" class="mono" font-size="12" letter-spacing="3.5" fill="#deb46c">AN ATLAS OF AGENT SKILLS</text>
  <text x="62" y="155" class="sans" font-size="70" font-weight="700" letter-spacing="-3" fill="#f3eddc">EVERYTHING</text>
  <text x="62" y="233" class="serif" font-size="78" font-style="italic" letter-spacing="1" fill="#deb46c">Skills.</text>
  <path d="M66 259H649" stroke="#385348"/>
  <text x="66" y="290" class="sans" font-size="15" fill="#b6c8bc" letter-spacing=".4">Curated by domain. Connected by knowledge.</text>
  <text x="66" y="316" class="mono" font-size="10" fill="#819b8e" letter-spacing="1.5">OPEN SOURCE  /  NATIVE LANGUAGES  /  ONE SHARED MAP</text>
  <path d="M755 52V308" stroke="#2b4338"/>
  <g>${spokes}${edges}</g>
  <circle cx="982" cy="176" r="120" fill="none" stroke="#476451" stroke-opacity=".8"/>
  <circle cx="982" cy="176" r="91" fill="none" stroke="#30473c" stroke-dasharray="2 8"/>
  <circle cx="982" cy="176" r="120" fill="none" stroke="#deb46c" stroke-width="2" pathLength="114" class="travel"/>
  ${labels}
  ${logoAt(926, 120, 112, animated)}
  <text x="982" y="337" class="mono" font-size="10" letter-spacing="2" text-anchor="middle" fill="#deb46c">${stats.volumes} VOLUMES. ONE LIVING LIBRARY.</text>`;
  return wrap(1200, 360, 'Everything Skills — an atlas of Agent Skills', 'A book-inspired E sits at the center of eleven connected domains. Slow pulses trace the shared knowledge map.', body, animated);
}

function metrics() {
  const items = [[stats.skills, 'CURATED SKILLS', '#deb46c'], [stats.volumes, 'DOMAIN VOLUMES', '#90b8a7'], [stats.edges, 'RELATION EDGES', '#e88f76'], [stats.repos, 'INDEXED REPOS', '#deb46c']];
  const body = `  <rect width="1200" height="138" rx="16" fill="#f3eddc"/>
  <rect x=".5" y=".5" width="1199" height="137" rx="15.5" fill="none" stroke="#d9d2bc"/>
  ${items.map(([value, label, color], i) => `<g transform="translate(${i * 300} 0)">${i ? '<path d="M0 27V111" stroke="#d9d2bc"/>' : ''}<circle cx="28" cy="29" r="3" fill="${color}"/><text x="42" y="33" class="mono" font-size="10.5" letter-spacing="1.6" fill="#526657">${label}</text><text x="27" y="95" class="serif" font-size="51" fill="#182c23">${fmt(value)}</text><path d="M28 114H271" stroke="#c9c5af"/></g>`).join('\n')}`;
  return wrap(1200, 138, 'Everything Skills at a glance', `${stats.skills} curated skills, ${stats.volumes} domain volumes, ${stats.edges} raw relation edges, and ${stats.repos} indexed external repositories.`, body, false);
}

function mobileHero(animated = true) {
  const body = `  <rect width="600" height="360" rx="20" fill="#111d1a"/>
  <rect x="1" y="1" width="598" height="358" rx="19" fill="none" stroke="#30473c"/>
  <text x="32" y="48" class="mono" font-size="12" letter-spacing="2.6" fill="#deb46c">AN ATLAS OF AGENT SKILLS</text>
  <text x="29" y="128" class="sans" font-size="62" font-weight="700" letter-spacing="-3" fill="#f3eddc">EVERYTHING</text>
  <text x="29" y="216" class="serif" font-size="80" font-style="italic" fill="#deb46c">Skills.</text>
  ${logoAt(433, 138, 108, animated)}
  <path d="M32 254H568" stroke="#385348"/>
  <text x="32" y="288" class="sans" font-size="19" fill="#b6c8bc">Curated by domain. Connected by knowledge.</text>
  <text x="32" y="325" class="mono" font-size="11" letter-spacing="1.2" fill="#819b8e">${stats.volumes} VOLUMES / ONE LIVING LIBRARY</text>`;
  return wrap(600, 360, 'Everything Skills', 'A compact book-inspired identity for the Agent Skills atlas.', body, animated);
}

function mobileMetrics() {
  const items = [[stats.skills, 'CURATED SKILLS'], [stats.volumes, 'DOMAIN VOLUMES'], [stats.edges, 'RELATION EDGES'], [stats.repos, 'INDEXED REPOS']];
  const body = `  <rect width="600" height="260" rx="16" fill="#f3eddc"/>
  <path d="M300 20V240M20 130H580" stroke="#d9d2bc"/>
  ${items.map(([n, label], i) => `<g transform="translate(${i % 2 * 300} ${Math.floor(i / 2) * 130})"><text x="26" y="35" class="mono" font-size="13" letter-spacing="1" fill="#526657">${label}</text><text x="24" y="100" class="serif" font-size="54" fill="#182c23">${fmt(n)}</text></g>`).join('\n')}`;
  return wrap(600, 260, 'Everything Skills statistics', `${stats.skills} skills, ${stats.volumes} volumes, ${stats.edges} relation edges, ${stats.repos} repositories.`, body, false);
}

function mobileOverview() {
  const steps = [['01  DISCOVER', 'Find the right capability', 'description + triggers'], ['02  CONNECT', 'Follow the knowledge graph', 'requires / related / combines_with'], ['03  COMPOSE', 'Build a useful workflow', 'load SKILL.md + combine']];
  const body = `  <rect width="400" height="440" rx="16" fill="#111d1a"/>
  ${steps.map(([title, subtitle, line], i) => `<g transform="translate(24 ${i * 136})"><text x="0" y="40" class="mono" font-size="12" letter-spacing="1.5" fill="#deb46c">${title}</text><text x="0" y="78" class="sans" font-size="22" fill="#f3eddc">${subtitle}</text><text x="0" y="110" class="mono" font-size="12" fill="#90b8a7">${line}</text><path d="M0 130H350" stroke="#30473c"/></g>`).join('\n')}`;
  return wrap(400, 440, 'Discover, connect, compose', 'A three-stage skill discovery and composition workflow.', body, false);
}

function overview(animated = true) {
  const cards = [
    { x: 32, title: '01  DISCOVER', subtitle: 'Find the right capability', lines: ['description + triggers', 'domain + tags'] },
    { x: 432, title: '02  CONNECT', subtitle: 'Follow the knowledge graph', lines: ['requires / related', 'combines_with'] },
    { x: 832, title: '03  COMPOSE', subtitle: 'Build a useful workflow', lines: ['load SKILL.md', 'combine focused skills'] },
  ];
  const body = `  <rect width="1200" height="188" rx="16" fill="#111d1a"/>
  ${cards.map(c => `<g><text x="${c.x}" y="42" class="mono" fill="#deb46c" font-size="11" letter-spacing="2">${c.title}</text><text x="${c.x}" y="82" class="sans" fill="#f3eddc" font-size="23" font-weight="600">${c.subtitle}</text><text x="${c.x}" y="119" class="mono" fill="#90b8a7" font-size="13">${c.lines[0]}</text><text x="${c.x}" y="143" class="mono" fill="#90b8a7" font-size="13">${c.lines[1]}</text></g>`).join('\n')}
  <path d="M364 94H399M389 86L399 94L389 102 M764 94H799M789 86L799 94L789 102" fill="none" stroke="#e88f76" stroke-width="2" stroke-linecap="round"/>
  <path d="M32 170H1168" stroke="#30473c"/>
  <path d="M32 170H1168" stroke="#deb46c" stroke-width="2" pathLength="114" class="travel"/>`;
  return wrap(1200, 188, 'Discover, connect, compose', 'Use metadata to find skills, follow their relationships, and compose focused skills into a workflow.', body, animated);
}

const BEGIN = '<!-- BEGIN GENERATED:brand -->', END = '<!-- END GENERATED:brand -->';
let readme = await fs.readFile(path.join(ROOT, 'README.md'), 'utf8');
const start = readme.indexOf(BEGIN), end = readme.indexOf(END);
if (start < 0 || end < start || readme.indexOf(BEGIN, start + BEGIN.length) >= 0 || readme.indexOf(END, end + END.length) >= 0)
  throw new Error('README needs exactly one ordered pair of brand markers.');
const tagline = lang === 'zh' ? '事以类聚，技以互见。为 AI Agent 编写的技能类书。' : 'An encyclopedic skill library for AI agents. Curated by domain. Connected by knowledge.';
const nav = lang === 'zh' ? ['技能总目', '关系图谱', '外部技能库', '贡献指南'] : ['Skill catalog', 'Knowledge graph', 'Skill repositories', 'Contributing'];
const block = `${BEGIN}
<p align="center">
  <a href="INDEX/catalog.md"><picture><source media="(prefers-reduced-motion: reduce) and (max-width: 600px)" srcset="assets/brand/hero-mobile-static.svg" /><source media="(prefers-reduced-motion: reduce)" srcset="assets/brand/hero-static.svg" /><source media="(max-width: 600px)" srcset="assets/brand/hero-mobile.svg" /><img src="assets/brand/hero.svg" alt="Everything Skills — a connected atlas of Agent Skills" width="1200" /></picture></a>
</p>

<p align="center"><strong>${tagline}</strong></p>

<p align="center">
  <a href="INDEX/catalog.md">${nav[0]}</a> · <a href="INDEX/graph.md">${nav[1]}</a> · <a href="INDEX/skill-repos.md">${nav[2]}</a> · <a href="CONTRIBUTING.md">${nav[3]}</a>
</p>

<p align="center">
  <picture><source media="(max-width: 600px)" srcset="assets/brand/stats-mobile.svg" /><img src="assets/brand/stats.svg" alt="${stats.skills} skills · ${stats.volumes} volumes · ${stats.edges} relation edges · ${stats.repos} indexed repositories" width="1200" /></picture>
</p>
${END}`;
readme = readme.slice(0, start) + block + readme.slice(end + END.length);
await fs.mkdir(OUT, { recursive: true });
for (const [name, content] of [ ['hero.svg', hero()], ['hero-static.svg', hero(false)], ['hero-mobile.svg', mobileHero()], ['hero-mobile-static.svg', mobileHero(false)], ['stats.svg', metrics()], ['stats-mobile.svg', mobileMetrics()], ['workflow.svg', overview()], ['workflow-static.svg', overview(false)], ['workflow-mobile.svg', mobileOverview()] ])
  await fs.writeFile(path.join(OUT, name), content);
await fs.writeFile(path.join(ROOT, 'README.md'), readme);
console.log(`Generated brand SVGs and README overview: ${stats.skills} skills / ${stats.volumes} volumes / ${stats.edges} edges / ${stats.repos} repos.`);
